x-airflow-common: &airflow-common
  build: .
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://Geouser:9632@192.168.1.8:5432/CryoDepthNetDb
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://Geouser:9632@192.168.1.8:5432/CryoDepthNetDb
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW_CONN_GLACIER_DB: postgresql://Geouser:9632@192.168.1.8:5432/CryoDepthNetDb
    AIRFLOW__WORKERS__BASE_URL: "http://airflow-api-server:8080/api/v2"
    AIRFLOW__CORE__INTERNAL_API_URL: "http://airflow-api-server:8080/api/v2"
    AIRFLOW__WORKERS__EXECUTION_API_SERVER_URL: "http://airflow-api-server:35999"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  depends_on:
    redis:
      condition: service_healthy

services:
  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate && airflow users create --username admin --password admin
      --firstname admin --lastname user --role Admin --email admin@example.com"
    restart: "no"

  airflow-api-server:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
      - "35999:35999"
    expose:
      - "8080"
      - "35999"
    environment:
      AIRFLOW__EXECUTION_API__HOST: "0.0.0.0"
      AIRFLOW__EXECUTION_API__PORT: "35999"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d celery@$$HOSTNAME"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-api-server:
        condition: service_started

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    depends_on:
      airflow-init:
        condition: service_completed_successfully